### ISSUE TITLE
Karten Datei schreiben/einlesen

### ISSUE THREAD

**Issue by carlobrok** [gbg-informatik/Spiel#1]

**Comment by can5502** [comment]
Schritt 1: JSON Datei schreiben größtenteils ausgeführt, muss aber verbessert werden.
Schritt 2 und 3: Muss nächstes Mal gemacht werden.

**Comment by can5502** [comment]
**Arbeitsschritte**

1. JSON Datei schreiben/erstellen (Erdem, Niklas)
2. Kachel aus Bildern erstellen (Nabil; mit Lenas Gruppe in Kontakt kommen)
3. Programm zum Auslesen der JSON Datei schreiben (Sophie)
4. Austausch innerhalb der Gruppe
_spätestens bis zum 15.01.2021_

**Comment by carlobrok** [comment]
Habe ein Tool programmiert mit dem man die Karte designen und exportieren kann.

**Comment by carlobrok** [comment]
Mit Branch loadMap erledigt
