### ISSUE TITLE
playerMovement

### ISSUE THREAD

**Issue by BastiSrd** [gbg-informatik/Spiel#2]
**Spielerbewegung**: anzeigen des eigenen Spielers und Übergabe von Koordinaten
**Pseudo Bewegung**: Koordinaten auf der Gesamtmap / nicht auf dem eigenen Bildschirm

**Comment by Frederik-Eberhard** [comment]
Spieler werden angezeigt und können sich alle bewegen. Alle Koordinaten werden an den Server übertragen und mit den Clients geteilt, die wiederum jeden Spieler an der korrekten Position anzeigen
