### ISSUE TITLE
Design der verschiedenen Kacheln

### ISSUE THREAD

**Issue by Thea36** [gbg-informatik/Spiel#5]
Wie sollen die verschiedenen Kacheln aussehen? Hier erste Designvorschläge für die verschiedenen Kacheln. Screenshots von verschiedenen Varianten.
Dazu gehören: der Boden, Wände, gute Items, schlechte Items, Knöpfe und Ähnliches.

**Comment by Thea36** [comment]
![image](https://user-images.githubusercontent.com/73578961/99505098-ac684780-2980-11eb-9988-8a44565299be.png)
Heute: Raumtrenner, nicht Mauer!

**Comment by Thea36** [comment]
![image](https://user-images.githubusercontent.com/73578961/100205126-fc0cbd00-2f04-11eb-94e7-431325d8b074.png)

So sieht die Mauer aus, wenn man verschiedene Teile zusammen setzt. Außerdem sind die Coop Platten zu sehen... sie sollen allerdings vor und nach den Mauern kommen (A davor, B danach)

**Comment by carlobrok** [comment]
Erste Versionen der Kacheln fertig
